#!/usr/bin/env node
"use strict";

/*
 * Renders docs/views/** from docs/records/**.
 *
 * Every file this writes is GENERATED and committed. It is committed so a
 * reader who is not running forge can still read the project on GitHub; it is
 * generated so that no human maintains it by hand. That second half is not a
 * preference. The file this replaces, a hand-maintained traceability table,
 * reached 342 KB on a real project with eight rows whose Status column held
 * narrative prose, and had its column boundaries destroyed once and rebuilt
 * cell by cell. A views guard hook denies writes under docs/views/ for exactly
 * this reason.
 *
 * DETERMINISM IS A CONTRACT. Same records in, same bytes out. `check` is a
 * byte comparison against what is on disk, so any nondeterminism here (a
 * timestamp, an unsorted map, a locale-dependent sort) turns `check` into a
 * gate that fails at random and gets switched off. Records arrive pre-sorted
 * by ID from the library; keep every other ordering explicit.
 *
 * Usage:
 *   node .forge/forge-views.js render [--only traceability|open-work|done-archive]
 *   node .forge/forge-views.js check [--if-present]
 *
 * Exit 0  views written, or `check` found them current
 * Exit 1  `check` found a view stale or hand-edited; stdout names it with a diff
 * Exit 2  render failed on an unresolvable edge; detail is deferred to the linter
 */

const fs = require("fs");
const path = require("path");
const lib = require("./forge-records-lib.js");

const BANNER = "<!-- GENERATED by forge-views.js from docs/records/. Do not edit. -->";

const VIEWS = ["traceability", "open-work", "done-archive"];

const FILENAME = {
  traceability: "traceability.md",
  "open-work": "open-work.md",
  "done-archive": "DONE-ARCHIVE.md",
};

function parseArgs(argv) {
  const opts = { command: argv[0], only: null, ifPresent: false, records: "docs/records", views: "docs/views" };
  for (let i = 1; i < argv.length; i += 1) {
    if (argv[i] === "--if-present") {
      opts.ifPresent = true;
    } else if (argv[i] === "--only") {
      opts.only = argv[i + 1];
      i += 1;
    } else if (argv[i] === "--records") {
      opts.records = argv[i + 1];
      i += 1;
    } else if (argv[i] === "--views") {
      opts.views = argv[i + 1];
      i += 1;
    } else {
      process.stdout.write("forge-views: unknown argument " + argv[i] + "\n");
      process.exit(2);
    }
  }
  if (opts.only && !VIEWS.includes(opts.only)) {
    process.stdout.write("forge-views: --only must be one of " + VIEWS.join(", ") + "\n");
    process.exit(2);
  }
  return opts;
}

function cell(value) {
  // A pipe inside a cell would break the table, which is one of the two ways
  // the hand-maintained predecessor was destroyed. Escape rather than trust.
  return String(value === undefined || value === null ? "" : value).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function header(title, note) {
  const out = [BANNER, "", "# " + title, ""];
  if (note) {
    out.push(note, "");
  }
  return out;
}

/*
 * Traceability: one row per live requirement, with what satisfies it and what
 * evidence closed it. Requirements are the rows because the question this view
 * answers is "is every requirement accounted for", not "what has been done".
 */
function renderTraceability(records) {
  const byId = new Map(records.map((r) => [r.data.id, r]));

  const satisfiedBy = new Map();
  for (const rec of records) {
    for (const id of rec.data.satisfies || []) {
      if (!satisfiedBy.has(id)) satisfiedBy.set(id, []);
      satisfiedBy.get(id).push(rec.data.id);
    }
  }

  const requirements = records.filter((r) => r.data.type === "requirement" && lib.isLive(r));

  const out = header(
    "Traceability",
    "One row per live requirement. A requirement with no satisfying record is a gap, " +
      "and the gap count below is what a release report quotes."
  );

  out.push("| Requirement | Status | Title | Satisfied by | Decided in |");
  out.push("|---|---|---|---|---|");

  for (const req of requirements) {
    const satisfiers = (satisfiedBy.get(req.data.id) || []).sort();
    const decided = satisfiers
      .map((id) => byId.get(id))
      .filter((r) => r && r.data.decided_in)
      .map((r) => r.data.decided_in);
    out.push(
      "| " + cell(req.data.id) +
        " | " + cell(req.data.status) +
        " | " + cell(req.data.title) +
        " | " + cell(satisfiers.join(", ")) +
        " | " + cell(Array.from(new Set(decided)).sort().join(", ")) +
        " |"
    );
  }

  const gaps = requirements.filter((r) => !satisfiedBy.has(r.data.id));
  out.push("");
  out.push("**" + requirements.length + " live requirements, " + gaps.length + " with no satisfying record.**");
  if (gaps.length) {
    out.push("");
    out.push("Gaps: " + gaps.map((r) => r.data.id).sort().join(", "));
  }
  out.push("");
  return out.join("\n");
}

/*
 * Open work: the whole live working set, and nothing that is closed. This is
 * the view that replaces reading a 700 KB backlog to find six open items.
 */
function renderOpenWork(records) {
  const out = header("Open work", "Everything still open. Closed work is in DONE-ARCHIVE.md.");

  const tasks = records.filter((r) => r.data.type === "task" && lib.isOpen(r));
  out.push("## Tasks (" + tasks.length + ")");
  out.push("");
  if (tasks.length) {
    out.push("| Task | Status | Title | Satisfies |");
    out.push("|---|---|---|---|");
    for (const t of tasks) {
      out.push(
        "| " + cell(t.data.id) +
          " | " + cell(t.data.status) +
          " | " + cell(t.data.title) +
          " | " + cell((t.data.satisfies || []).join(", ")) +
          " |"
      );
    }
  } else {
    out.push("None.");
  }
  out.push("");

  const uxd = records.filter((r) => r.data.type === "uxd" && lib.isOpen(r));
  out.push("## UX debt (" + uxd.length + ")");
  out.push("");
  if (uxd.length) {
    out.push("| Defect | Severity | Status | Title |");
    out.push("|---|---|---|---|");
    // Severity order, worst first, then by ID. An alphabetical severity sort
    // would put `blocks` after `degrades`, which is exactly backwards for a
    // list whose job is to be read top down before a release.
    const rank = { blocks: 0, degrades: 1, finish: 2 };
    const sorted = uxd.slice().sort((a, b) => {
      const ra = rank[a.data.severity] === undefined ? 9 : rank[a.data.severity];
      const rb = rank[b.data.severity] === undefined ? 9 : rank[b.data.severity];
      return ra - rb || String(a.data.id).localeCompare(String(b.data.id));
    });
    for (const d of sorted) {
      out.push(
        "| " + cell(d.data.id) +
          " | " + cell(d.data.severity) +
          " | " + cell(d.data.status) +
          " | " + cell(d.data.title) +
          " |"
      );
    }
  } else {
    out.push("None.");
  }
  out.push("");

  const gaps = records.filter((r) => r.data.type === "requirement" && lib.isLive(r) && r.data.status === "proposed");
  out.push("## Requirements not yet approved (" + gaps.length + ")");
  out.push("");
  out.push(gaps.length ? gaps.map((r) => "- " + r.data.id + " " + r.data.title).join("\n") : "None.");
  out.push("");
  return out.join("\n");
}

/*
 * Done archive: closed work, newest first. This grows without bound and that is
 * fine, because nothing reads it to decide what to do next. That is the whole
 * point of separating it from open-work.md.
 */
function renderDoneArchive(records) {
  const out = header("Done", "Closed work, newest first. Nothing here is live.");

  const done = records
    .filter(
      (r) =>
        (r.data.type === "task" && (r.data.status === "closed" || r.data.status === "abandoned")) ||
        (r.data.type === "uxd" && (r.data.status === "fixed" || r.data.status === "slipped"))
    )
    .slice()
    .sort((a, b) => String(b.data.date).localeCompare(String(a.data.date)) || String(b.data.id).localeCompare(String(a.data.id)));

  out.push("| Date | Record | Status | Title | Closes |");
  out.push("|---|---|---|---|---|");
  for (const r of done) {
    out.push(
      "| " + cell(r.data.date) +
        " | " + cell(r.data.id) +
        " | " + cell(r.data.status) +
        " | " + cell(r.data.title) +
        " | " + cell((r.data.closes || []).join(", ")) +
        " |"
    );
  }
  out.push("");
  out.push("**" + done.length + " closed records.**");
  out.push("");
  return out.join("\n");
}

const RENDERERS = {
  traceability: renderTraceability,
  "open-work": renderOpenWork,
  "done-archive": renderDoneArchive,
};

const opts = parseArgs(process.argv.slice(2));
const recordsDir = path.resolve(process.cwd(), opts.records);
const viewsDir = path.resolve(process.cwd(), opts.views);

if (!fs.existsSync(recordsDir)) {
  if (opts.ifPresent) {
    process.stdout.write("forge-views: no record set at " + opts.records + ", nothing to render\n");
    process.exit(0);
  }
  process.stdout.write("forge-views: no record set at " + opts.records + "\n");
  process.exit(2);
}

const { records, errors } = lib.readRecords(recordsDir);
if (errors.length) {
  process.stdout.write(
    "forge-views: " + errors.length + " record(s) could not be parsed. Run forge-records-lint.js for detail\n"
  );
  process.exit(2);
}

const wanted = opts.only ? [opts.only] : VIEWS;
const rendered = new Map();
for (const name of wanted) {
  rendered.set(name, RENDERERS[name](records));
}

if (opts.command === "render") {
  fs.mkdirSync(viewsDir, { recursive: true });
  for (const [name, text] of rendered) {
    fs.writeFileSync(path.join(viewsDir, FILENAME[name]), text);
  }
  process.stdout.write("forge-views: rendered " + Array.from(rendered.keys()).join(", ") + "\n");
  process.exit(0);
}

if (opts.command === "check") {
  const stale = [];
  for (const [name, text] of rendered) {
    const file = path.join(viewsDir, FILENAME[name]);
    let onDisk = null;
    try {
      onDisk = fs.readFileSync(file, "utf8");
    } catch (err) {
      stale.push({ name, file, reason: "missing", diff: null });
      continue;
    }
    if (onDisk !== text) {
      stale.push({ name, file, reason: "differs from what the records render", diff: firstDifference(onDisk, text) });
    }
  }

  if (stale.length) {
    const out = ["forge-views: " + stale.length + " view(s) out of date", ""];
    for (const s of stale) {
      out.push("  " + path.relative(process.cwd(), s.file) + "  " + s.reason);
      if (s.diff) {
        out.push("    line " + s.diff.line);
        out.push("    on disk:  " + s.diff.a);
        out.push("    rendered: " + s.diff.b);
      }
    }
    out.push("");
    out.push("Run: node .forge/forge-views.js render");
    process.stdout.write(out.join("\n") + "\n");
    process.exit(1);
  }

  process.stdout.write("forge-views: all views current\n");
  process.exit(0);
}

process.stdout.write("Usage: forge-views.js render|check [--only <view>]\n");
process.exit(2);

/*
 * The first differing line, which is what a reader needs to see whether a view
 * is stale because the records moved on or because somebody hand-edited it.
 */
function firstDifference(a, b) {
  const la = a.split("\n");
  const lb = b.split("\n");
  const max = Math.max(la.length, lb.length);
  for (let i = 0; i < max; i += 1) {
    if (la[i] !== lb[i]) {
      return { line: i + 1, a: la[i] === undefined ? "(end of file)" : la[i], b: lb[i] === undefined ? "(end of file)" : lb[i] };
    }
  }
  return null;
}
